const assert = require("node:assert/strict");
const journey = require("./training-journey.js");
const makeRun = () => ({ turn: 0, limit: 20, completed: false, teamIds: ["ren", "yui", "mio", "honoka"] });
const run = makeRun();
journey.ensure(run);
assert.equal(journey.select(run, "power"), true);
run.turn = 1;
let result = journey.advance(run, "power", ["ren"], 3);
assert.equal(result.rewards.length, 2, "A wish rewards its owner once");
assert.equal(journey.select(run, "bond"), false, "Cannot change route after committing a turn");
run.turn = 2;
result = journey.advance(run, "power", ["yui"], 0);
assert.equal(result.rewards.length, 0);
run.turn = 5;
result = journey.advance(run, "rest", run.teamIds, 0);
assert.equal(result.rewards.length, 4);
assert.ok(result.rewards.every((reward) => reward.amount === 5));
assert.equal(journey.advance(run, "rest", run.teamIds, 0).rewards.length, 0, "No duplicate milestone reward");
assert.equal(run.journey.wins, 1);
const resumed = JSON.parse(JSON.stringify(run));
journey.ensure(resumed);
assert.equal(resumed.journey.stage.end, 10);
assert.equal(resumed.journey.stage.wishId, "yui");
assert.equal(resumed.journey.wins, 1);
journey.select(resumed, "bond");
resumed.turn = 6;
journey.advance(resumed, "bond", ["ren"], 0);
resumed.turn = 7;
journey.advance(resumed, "bond", ["ren"], 0);
resumed.turn = 10;
result = journey.advance(resumed, "rest", resumed.teamIds, 0);
assert.equal(result.rewards.length, 0, "One participant cannot complete a team goal");
assert.equal(resumed.journey.wins, 1);
const legacy = { ...makeRun(), turn: 13 };
journey.ensure(legacy);
assert.equal(legacy.journey.stage.start, 13);
assert.equal(legacy.journey.stage.end, 15);
legacy.turn = 20;
legacy.completed = true;
journey.ensure(legacy);
assert.notEqual(legacy.journey.stage.end, 25, "Completed saves do not start another chapter");
console.log("Training journey: rewards, locking, team goal, resume, legacy save and completion passed.");
